# Support the author by using the funding links below.
# Developed and maintained by Mehdi Davoodi with the help of awesome contributors.
# Buy Me a Coffee: buymeacoffee.com/mehdidavoodi

buy_me_a_coffee: mehdidavoodi

# Sponsoring this project means a lot to me, this will help me to continue building great open-source projects just like this.
